### PR TITLE
Use only GPLv3+ license

### LINKED ISSUE #38: Invalid SPDX license expression in activity.info
https://github.com/sugarlabs/memorize-activity/blob/master/activity/activity.info contains the following license.

```
license = GPLv2+;GPLv3+
```

which is not valid SPDX license expression. Hence it's reported as non-foss app in GNOME Software. 

Refer https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2540

### PR DESCRIPTION
**Pull request by chimosky**
Fixes #38 @quozl kindly review.

### CODE REVIEW

**Comment by quozl** [comment]
As the GPLv3 is more restrictive than the GPLv2, I'd like to see consent from the authors.

**Comment by chimosky** [comment]
I don't have access to any of the authors, if you do, could you reach out to them?

Also not sure if Muriel is still at the olpc as his email is there.

**Comment by quozl** [comment]
I've two very old addresses for Muriel.

I don't think I have any unusual access to authors.

Given your comment in another activity, is it necessary to relicense?

**Comment by chimosky** [comment]
I don't think it's necessary to relicense tbh.

**Pull request closed without merging**
